### ISSUE TITLE
Support on windows

### ISSUE THREAD

**Issue by saurabhPV** [wolfSSL/wolfcrypt-py#12]
Does it support windows? I am trying to run an existing project that uses this lib. When I try to install, it throws error failed building wheel for wolfcrypt.

Unfortunately location it shows to look for logs doesn't exist.

**Comment by dgarske** [comment]
Hi @saurabhPV , Thanks for the issue report. Officially `wolfcrypt-py` is not yet supported on Windows, despite python being cross-platform.

We recently did some work (although experimental) to try and use cibuildwheels to support wolfcrypt-py on Windows here: https://github.com/wolfSSL/wolfcrypt-py/pull/13

Looking forward to your feedback.

FYI: I recently wrote up a good overview for installing wolfcrypt-py using standard "linux" here:
https://github.com/wolfSSL/wolfBoot/blob/master/docs/Signing.md#install-python3

Thanks,
David Garske, wolfSSL

**Comment by saurabhPV** [comment]
Tahnks a lot David!
I tried to add this branch using

pipenv install -e git+https://github.com/danielinux/wolfcrypt-py.git@cibuildwheel#egg=wolfcrypt (I can see in pipfile wolfcrypt = {editable = true,git = "https://github.com/danielinux/wolfcrypt-py.git",ref = "cibuildwheel"})

 

but it fails to lock the dependencies

I can see below error in the console

PermissionError: [WinError 5] Access is denied:  …\\wolfcrypt\\.git\\objects\\pack\\pack-c2d1ff773ef7b7edf9a0d9a7f2b8a39b5ca75410.idx'
I am running this as an administrator so I am not sure why this error occurred.
I am trying to run it on windows 10, python 3.6

**Comment by dgarske** [comment]
Hi @saurabhPV , that looks like a .git contention issue... meaning Git is already locked and another process is trying to use it.

@danielinux , do you have any tips you could share?

Thanks,
David Garske, wolfSSL

**Comment by danielinux** [comment]
Hello @saurabhPV - The 'ciBuildwheel' branch is just an attempt to find a simple way to create packages under windows and automate the process for the next releases. Unfortunately I haven't been able to build the package under windows yet, so I don't have any tips to share.

On the other hand, should you get any progress with the procedure please share back your findings, as I am still trying to find the best way to create the official windows packages that will be distributed via pip.

Thanks,

-- 
Daniele

**Comment by kakooloukia** [comment]
Hi @danielinux ,

Is there any update concerning Windows ? Because the library still does not build...
I assume the 'ciBuildwheel' branch had been merged because it is not available any-more.

If someone succeed to install it on windows, i would be glad to get some advice :)

Thanks in advance,
Yoann

**Comment by dgarske** [comment]
@kakooloukia ,

No progress on the wolfCrypt-python issues with Windows.

To help with the Windows python issues we implemented C versions of the key tools and created a Visual Studio project. See here: https://github.com/wolfSSL/wolfBoot/blob/master/docs/Signing.md#c-key-tools

Thanks,
David Garske, wolfSSL

**Comment by saurabhPV** [comment]
@kakooloukia if it helps , I am running my project using docker thanks to volume mounting and hot reload in python it's doesn't cause a much issue.

**Comment by LinuxJedi** [comment]
As an update to this, once we have PR #37 in we should have full Windows support.

**Comment by LinuxJedi** [comment]
Windows support has been merged. Closing this for now. Please feel free to reopen or open a new ticket if you come across any issues.
