### ISSUE TITLE
Python wheels (prebuilt binaries) missing Sha-3 support

### ISSUE THREAD

**Issue by nkapu** [wolfSSL/wolfcrypt-py#18]
Python wheels (prebuilt binaries) missing Sha-3 support. Published python wheels at pypi (https://pypi.org/project/wolfcrypt/#files) have not yet been compiled with Sha-3 support.

**Comment by tmael** [comment]
Hi @nkapu,

Thanks for reaching out to wolfSSL support! 
We've added support for Sha-3 with PR #11 
You are right that the Python wheels (prebuilt binaries) need updating.  We'll look into it. 

Thanks,
Tesfa

**Comment by tmael** [comment]
Closing since we are tracking it internally.
