### ISSUE TITLE
Padded input requirement for CTR AES mode.

### ISSUE THREAD

**Issue by Waotest** [wolfSSL/wolfcrypt-py#59]
https://github.com/wolfSSL/wolfcrypt-py/blob/1c242652a799190b55cc20964135297357e00b67/wolfcrypt/ciphers.py#L184C13-L184C13

Is this really required ?

**Comment by embhorn** [comment]
Hi @Waotest 

Thanks for contacting wolfSSL. Could you tell us a bit about your project using wolfCrypt Python?

I'm reviewing your question with the team.

Thanks,
@embhorn

**Comment by Waotest** [comment]
im encrypting in python and decrypting in c. i need the file length to stay the same that's why i use ctr mode. but your python wrapper requires the input to be multiple of block size which should not be required for ctr aes.

**Comment by embhorn** [comment]
Hi @Waotest 

Please confirm if this resolves the issue with AES CTR sizes:
https://github.com/wolfSSL/wolfcrypt-py/pull/60
